"""Build js/astro/deltat.js from the US Naval Observatory's ΔT = TT − UT1 series.

    python3 tests/make_deltat.py

Sources (maia.usno.navy.mil/ser7/): historic_deltat.data (1657–1984, half-yearly, from telescopic
timings of lunar occultations), deltat.data (monthly, measured by the IERS since 1973) and
deltat.preds (the official prediction, ~8 years ahead). Standard library only.
"""
import os, urllib.request

BASE = 'https://maia.usno.navy.mil/ser7/'
get = lambda f: urllib.request.urlopen(BASE + f, timeout=60).read().decode().splitlines()

rows = {}
for line in get('historic_deltat.data'):
    f = line.split()
    try: y, dt = float(f[0]), float(f[1])
    except (ValueError, IndexError): continue
    if y < 1973: rows[round(y, 3)] = round(dt, 1 if y < 1900 else 2)
measured = []
for line in get('deltat.data'):
    f = line.split()
    if len(f) == 4: measured.append((int(f[0]) + (int(f[1]) - 1) / 12, float(f[3])))
for i, (y, dt) in enumerate(measured):
    if i % 3 == 0 or i == len(measured) - 1: rows[round(y, 3)] = round(dt, 2)
last_measured = measured[-1][0]
for line in get('deltat.preds')[1:]:
    f = line.split()
    if len(f) >= 3 and float(f[1]) > last_measured + 0.2: rows[round(float(f[1]), 3)] = round(float(f[2]), 2)

pairs = sorted(rows.items())
body = ',\n'.join('  ' + ', '.join(f'{y:g}, {dt:g}' for y, dt in pairs[i:i + 8]) for i in range(0, len(pairs), 8))
m = measured[-1]
out = f"""// ΔT = TT − UT1: how far Earth's rotation lags a uniform clock. Generated by tests/make_deltat.py
// from the US Naval Observatory series (telescopic timings from 1657, IERS measurements from 1973,
// the official prediction to {pairs[-1][0]:.2f}). Outside the table the Espenak & Meeus polynomials of NASA's
// Five Millennium Canon take over, blended in so that ΔT stays continuous.
import * as A from '../../vendor/astronomy.min.js';

// decimal year, ΔT (s)
const T = [
{body},
];
export const DT_FIRST = T[0], DT_LAST = T[T.length - 2];
/** the last month with a measured value, as a UTC ms timestamp; later values are predictions */
export const DT_MEASURED_UNTIL = Date.UTC({int(m[0])}, {round((m[0] % 1) * 12)}, 1);

const EM = y => A.DeltaT_EspenakMeeus((y - 2000) * 365.25);
const FADE_BEFORE = 1600, FADE_AFTER = 2150;

/** ΔT in seconds for `ut` days since J2000 (astronomy-engine's DeltaTimeFunction signature) */
export function deltaT(ut) {{
  const y = 2000 + ut / 365.25;
  if (y < DT_FIRST) {{
    const off = T[1] - EM(DT_FIRST);
    return EM(y) + (y > FADE_BEFORE ? off * (y - FADE_BEFORE) / (DT_FIRST - FADE_BEFORE) : 0);
  }}
  if (y >= DT_LAST) {{
    const off = T[T.length - 1] - EM(DT_LAST);
    return EM(y) + (y < FADE_AFTER ? off * (FADE_AFTER - y) / (FADE_AFTER - DT_LAST) : 0);
  }}
  let lo = 0, hi = T.length / 2 - 1;
  while (hi - lo > 1) {{ const mid = (lo + hi) >> 1; if (T[2 * mid] <= y) lo = mid; else hi = mid; }}
  const y0 = T[2 * lo], y1 = T[2 * hi], k = (y - y0) / (y1 - y0);
  return T[2 * lo + 1] + k * (T[2 * hi + 1] - T[2 * lo + 1]);
}}
"""
open(os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'js', 'astro', 'deltat.js'), 'w').write(out)
print(len(pairs), 'points', pairs[0], pairs[-1], 'measured until', m)
