"""Build js/astro/rotation.js from NAIF's planetary constants kernel pck00011.tpc, which carries
the IAU WGCCRE 2015 rotation models (Archinal et al. 2018, with later corrections).

    python3 tests/make_rotation.py

Standard library only.
"""
import os, re, json, urllib.request

URL = 'https://naif.jpl.nasa.gov/pub/naif/generic_kernels/pck/pck00011.tpc'
txt = urllib.request.urlopen(URL, timeout=60).read().decode()
data = '\n'.join(re.findall(r'\\begindata(.*?)(?=\\begintext|\Z)', txt, re.S))
num = re.compile(r'^[-+]?[0-9.]+([ED][-+]?[0-9]+)?$', re.I)
vals = {m.group(1): [float(x.upper().replace('D', 'E')) for x in m.group(2).split() if num.match(x)]
        for m in re.finditer(r'(\w+)\s*=\s*\(([^)]*)\)', data)}

BODIES = {'Phobos': 401, 'Deimos': 402, 'Io': 501, 'Europa': 502, 'Ganymede': 503, 'Callisto': 504, 'Titan': 606}
systems, models = {}, {}
for name, naif in BODIES.items():
    sysid = naif // 100
    if sysid not in systems:
        ang = vals[f'BODY{sysid}_NUT_PREC_ANGLES']
        deg = int(vals.get(f'BODY{sysid}_MAX_PHASE_DEGREE', [1])[0])
        systems[sysid] = [ang[i:i + deg + 1] for i in range(0, len(ang), deg + 1)]
    g = lambda k, n=3: (vals.get(f'BODY{naif}_{k}', []) + [0.0] * n)[:n] if n else vals.get(f'BODY{naif}_{k}', [])
    models[name] = {'sys': sysid, 'ra': g('POLE_RA'), 'dec': g('POLE_DEC'), 'pm': g('PM'),
                    'nra': g('NUT_PREC_RA', 0), 'ndec': g('NUT_PREC_DEC', 0), 'npm': g('NUT_PREC_PM', 0)}

out = f"""// IAU rotation models (WGCCRE 2015, Archinal et al. 2018) of the moons astronomy-engine does not
// orient. Generated by tests/make_rotation.py from NAIF's pck00011.tpc; do not edit by hand.
//
// Pole right ascension and declination (ICRF, degrees) and prime meridian angle W, each a polynomial
// in time plus periodic terms in the planet system's "nutation–precession" angles:
//   α = ra0 + ra1 T + ra2 T² + Σ nra_k sin θ_k     T: Julian centuries TDB since J2000
//   δ = dec0 + dec1 T + dec2 T² + Σ ndec_k cos θ_k
//   W = pm0 + pm1 d + pm2 d² + Σ npm_k sin θ_k     d: days TDB since J2000
//   θ_k = c0 + c1 T (+ c2 T²)

// θ_k coefficients per planet system (NAIF system id: 4 Mars, 5 Jupiter, 6 Saturn)
export const ANGLES = {json.dumps({str(k): v for k, v in systems.items()})};

export const MODELS = {{
{chr(10).join(f'  {n}: {json.dumps(m)},' for n, m in models.items())}
}};

const D = Math.PI / 180;
const poly = (c, x) => c[0] + c[1] * x + c[2] * x * x;

/** {{ pole: unit vector (ICRF/EQJ), W: degrees }} for `t` days TT (≈ TDB) since J2000, or null */
export function iauRotation(name, t) {{
  const m = MODELS[name];
  if (!m) return null;
  const T = t / 36525, th = ANGLES[m.sys].map(c => (c[0] + c[1] * T + (c[2] || 0) * T * T) * D);
  let ra = poly(m.ra, T), dec = poly(m.dec, T), W = poly(m.pm, t);
  m.nra.forEach((a, k) => {{ ra += a * Math.sin(th[k]); }});
  m.ndec.forEach((a, k) => {{ dec += a * Math.cos(th[k]); }});
  m.npm.forEach((a, k) => {{ W += a * Math.sin(th[k]); }});
  const cd = Math.cos(dec * D);
  return {{ pole: [cd * Math.cos(ra * D), cd * Math.sin(ra * D), Math.sin(dec * D)], W }};
}}
"""
open(os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'js', 'astro', 'rotation.js'), 'w').write(out)
for n, m in models.items(): print(n, m['pm'], len(m['npm']))
